language: php
php: 5.6
branches:
  except:
    - master
    - /^feature\//
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
      urls:
        - https://webhooks.gitter.im/e/4205227638a80c69f2e0
      on_success: always
      on_failure: always
      on_start: never
  slack:
      secure: cHbnVNoDkoOMPCs1lzD4u3NA0ALfQMtXQdkntADSCqgleHHuRS1SmSGU2o7lj1HkOLGNDEyIHmpeQMaZBvvVG1iq3qVHWROnIx9lV2uuXPRDB7xlFSZ71pxr2GRG2fzO5DVIye+sMsyie2A5RCQ6NHaCzO6B3Q0pss0pza3TZ8sYXbezkGoEI4NLXPKCZaQboZAA8uPsiAPg1G4KGazDYkXQ2jg5lk9Uokf51OehzbkpAYfn2f8A+ZxJ8T48LrFC8sLxl+cDWRRdRneX32WCzksoSlOhsbRsLkf8IZVWxLlX9QC1QMg8JIe6/tU98fPMZBF3ZWuSNuLVOHpMAr+/fXxqwBW7bss+vYR/bW5L7oRSyJx5tMAwR5BOcSvIUCXOs4Tq00JMELbn7oL/cesie6L3SJcuxtXPggOdRrhMfX5ehRvFETp+mAbIDtr19+JRhTkjLpMIXx7y2IrJijtCxqAavhJ2iMGzpDp343tRCTNYml/yOB23VnyWSI/43Y87pqIa93GfddbcTidSbnTO6bdiSoIRumiFYdmpX/plmH/jdOxjBeDo6uKc2+KoJgdgr7HIGdOQRdQdqoOMF8H+ZxiUmCs3000pzEsb0ugV7yNubRBboVSEKnegeDWpj04V6iQCAWZx6PHkJWRb9a7XnGyPS3f0YReh5blL9NpZYno=
env:
  global:
    # GH_TOKEN
    - secure: "GIFHCpRBw07hm/RwDUbeh1EZS3nUCRFnsAhyeBm02a5dKbCCIrAUoI5HVjTPyFiG/UKaRo3u/7byA3ROmXgVE48Hg5n4E3+ga8zOwdRdXql7V6pwu4bII4Kr+4qFgIDkn8ca1Ut1bxKQZI/NP/FR73pZ/pst/rtw27M4Au/PZSHAtAkMF1KSqcRSfvggAtqnhh3xFTFx13XvakX7zpP1AyD1Yft4dHhhZN+BHTxQgRrl+fJLky1MAwIwOl1xOF1VH+RQDdh3yXLHMfbznTjdeE9vJCiEjnZPUgZ+aXusLj1bJoNgrRNVCCikrOMLFK854YxxzGuzRtN/6xhcB/8LeFypw8jhHNnswJ5TX8heB7i4Jbu/7OTCk5/Ew0uG6kveTtvWsAOmVZZAqSl4Z/hZowCAavXy2X1DmZpsjQ0ljxZC271a5UQpI5HF7EKVoFhzvxyxZrxlUYSSDFTOoNGauKvsZbtgz6A0eAQOpjtuWXRTYnbxsOEZFuZCuOwUU6EdDtSA0RIpxnUI3qwn26+GzGTaaxjwTQ+ZtytmHaddC3jgKZ9EfZB6yOUeXXdnI+h0coSR8lp4yjOU/ZWnA9n96+fMqwnR5zCbxJeErhI8RJFWJL1/so1k0wq3t4OixVjDGY1rJkkugD8AnIUEPgB/gfGtF5t6J4WGrpFhWzej9/c="
    # BAMBOO_SITE
    - secure: "I35JOZgBkZvetCp+Twfeq1aXvDmNqR7N6VTsLii1d6oV4nB93qcDcgEj9wO+Ou3vqW/RnDVG6e+KJmgl+/HdFd+dVmaJJGsxRxBkUQ7Wz1y/5JGy8dodwwBp/aBxz47NCqmgO22MYA8prEo8wverwmtxJRfBXU0KChfTGzwf60P/ipqrYY4kxc6hAH1X5S9wzJN9YgkFFfo4o267mCvo40N3rvrkgZg9PRy5Ok67EIqF2xfVkESORGQIJ0flqzONz32GOsinpQtU9qQbNtABQdnjwhch51HhW5mlM0LgvcIqJcDWOG3shd49rkxHmiEm2m3UiJTL1g2bdX36lAYKi0CK6j/vfF9uXfenCBObQq40HgxRlrICK/cQcRgdm/rIELOqqIMT+b+5OAWeoDjEJxIn119ye6G9k2FNrUjkf+BeWmhiuG3nNtmgQg/UuUxDPEsaY9MKsi3Fupv0jM5/+H7FmVJFOtSyubw1kSf/v2NlD9ee2qoWFwqPsSCUa5TGPblhEtD6qFBUXMyF0IXo5qmpXFZR0bWDzdiGlvkqlsoNCAV41sPDCXQWQy4xYNmExjpjzC55FGhgN2KC8e03KedXfYIKOMr/ei0XZW/fIoL4OmSprPYky3E2hQloym1IT02Mxsao/e3xELW97aMDig0ORcr5ckbah5gnVNUg33A="
    # BAMBOO_DEPLOY
    - secure: "PaqUd7fcOF9zQ68E1uRbZtigh+2u7QDoczBt/WqE6F75Ja1gbGadTqwvy28JdQbBhVjqkGh7MwkEJ5DvHLGKQQjuIbDRRuV5vNoWDRugkuw2m9io7M/3Af9vys7RU2MFst7zGeD7a0xdDctgg3guk+MOHacWPMiL6KzRgPce1HmTxfejXeJpG6R5opVQSv2H97024yybQkW/7iieso9wG3saiH7RUMfjdtdo7BLhR99wS1im7bbfA5KPyUGcOl64HmFDMYE3GaxODM/gTjB3CRLSptMl6kFAAwH8EoEGxUf0tzU019iRHQOmcF5fbH+8BBe2xnI931V1AXAT/xieI1SffHzUHqYbtnF3Rc1UhEG6UOwPNLzlyz0J6j+DtwhwF/3rHCVCnilb4WhKXWeUGs4n6ijwN2oFqN9o449kLESZoyYXDJQ1N9TRqAzqRBWa3u0l+g9ylf1njKF5QIq7CziU5xgnYLp7Qi0qDeKItUmv3+KVaVKoYVI9uERlXLKdI5wWCG3BQnWnRUZqogmMcrkT/9DbmfJ93g9akMSMNpnDERj6/V+d/hdJk2rMYI1CAGvQWouPRpLOoIingtu8NdOhSO8VCzLLD+6aLHhe+i0XlgEMEL0SvQBRGhbd7DOYtc/kLbWLkY0LbhCdgbePIDwEbfXPpwOf+rGOS/zMfuc="
before_install:
  - nvm install stable
  - nvm use stable
  - composer self-update
  - npm config set spin false
  - npm install -g yarn
  - if [ ! -z "$TRAVIS_TAG" ]; then
      gem install sass;
      yarn global add gulp;
    fi
install:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      yarn;
      gulp -up;
    fi
  - cd $TRAVIS_BUILD_DIR/src/platforms/joomla && composer install --no-dev;
  - cd $TRAVIS_BUILD_DIR/src/platforms/wordpress && composer install --no-dev;
  - cd $TRAVIS_BUILD_DIR/src/platforms/grav && composer install --no-dev;
  - cd $TRAVIS_BUILD_DIR/src/platforms/prime && composer install --no-dev;
  - cd $TRAVIS_BUILD_DIR/bin/build && composer install --no-dev
script:
  - export SHORT_COMMIT=$(echo $TRAVIS_COMMIT | cut -c1-9)
  - echo "Branch ($TRAVIS_BRANCH)"
  - cd $TRAVIS_BUILD_DIR/bin/build
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      php build.php dev -Dpackage_dir=$TRAVIS_BUILD_DIR/../repo_pkgs -Dxml.version=dev-$SHORT_COMMIT -Dstr.fileversion=_develop;
    elif [ ! -z "$TRAVIS_TAG" ]; then
      php build.php prod -Dpackage_dir=$TRAVIS_BUILD_DIR/../repo_pkgs -Dxml.version=$TRAVIS_TAG;
    else
      echo "($TRAVIS_BRANCH) is not a supported branch for builds";
    fi
before_deploy:
  - export PROJ_PKGS_PATH=$TRAVIS_BUILD_DIR/../repo_pkgs
  - export PROJ_PKGS=$HOME/build/$TRAVIS_REPO_SLUG/../repo_pkgs/*.zip
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then
        FILES_PATH=$PROJ_PKGS_PATH;
        JSON="{";
        FILES=$FILES_PATH/*.zip;
        COUNT=`ls $FILES 2>/dev/null | wc -l | awk '{print $1}'`;
        COMMIT=$TRAVIS_COMMIT;
        SHORT_COMMIT=$(echo $COMMIT | cut -c1-9)
        CURRENT_DATE=`date +%s`

        JSON+="\"count\":$COUNT,";
        JSON+="\"commit\":\"$COMMIT\",";
        JSON+="\"commit_short\":\"$SHORT_COMMIT\",";
        JSON+="\"date\":\"$CURRENT_DATE\",";
        JSON+="\"files\":[";

        i=0;
        for file in ${FILES[@]}; do
            i=$(($i + 1));
            SIZE=`wc -c < $file | awk '{print $1}'`;
            DATE=`stat --format=\"%m\" $file`;
            JSON+="{";
            JSON+="\"file\":\"${file##*/}\",";
            JSON+="\"size\":$SIZE,";
            JSON+="\"date\":$DATE";
            JSON+="}";

            if [ $i != $COUNT ]; then
                JSON+=",";
            fi
        done;
        JSON+="]}";

        echo $JSON > "$FILES_PATH/map.json";
      fi
deploy:
  - provider: releases
    api_key:
      secure: "KgEZx0dHoPLOYj9T087flZKgaf4ggasJcd/DOjHjsXKhjyLYuWZNLOdJaT0MQ+UJ2RwzW+7ESR1lquwEqUN8uPFaA05SZwrCyJU1pOgTYqunM+Sz+lRWANMjgwtGNAQvPfTTAoaKZxrOVSMxv0U2OBAHE2lEsDvz7kwCuHbsoU3/xY144ecUG2lWItHjxQr2X7GmApBgCZ63OPaHK/NP1a8xtkQT+kTfKRHIZwPCyRplSRhqaa8ftQoi5SynaHtECi9/RYCRp3wgclbCPHRH3Eez4li+AdE8Q/X+LK/jmIYqOUWvq8IpS0ePg67fuE4cBNLYBrbPWgSPfUka3/61KyGRTw+2ofdf9eMOtJQa7JZUSWWUEeeyeBFIomNvY40nWSmC+T/l5EixIwBFF7CzVatnDPCz3w4gPYxAVwQjTtKqqFu6ZfeQNp0asj9OqukF3nJbN42iuIh6vxHxIQ6U3WMo+0t507i0rYf3Esl3YGlMVUuN7mNlWNv5eKrfD2CLHeBiDvo6SRCdYpgLu6FMBnwM2Fadlm51nAN/tpSxXEA1gUoVT3rJ8e6vnFcdy1ZHq1DPMtiZ8oMLBtdq8lcDs8DzKqCwImfmsDtM7M040JG/MuB5kVUXLcA5ycRCh1piDUAqITmvPucYHO8hT63cMZHwcxlqw1Ta3ckB4Ng3Eqg="
    skip_cleanup: true
    file_glob: true
    file: "${PROJ_PKGS}"
    on:
      repo: gantry/gantry5
      tags: true
  - provider: s3
    access_key_id: AKIAIGEIWVFNBMVSH2UA
    secret_access_key:
      secure: "DP32BDS3fk7/tLsZxj5CjiAT5GLHQFNOFte9Rds7eird+xqOSqUXHVplkOSVPKCt6V3CIO3wtxe97T4cuxtoobwVlwF8WRmrS4x98u2sLIS9lSZZzDg/W8tkLjOmW9QOKFtBEykj1z1i9nYDlhKFDtGNIkN7juZUz5UZ2S3Unwsm94vcm8ATghXGclwfib329I+7GVIA24PMUv2ETl0PGs+s+D1KmhXeU5UwharxnM+X4kyIsCBPrxXX+2QfAiSrjqKwHfzGQjRJIAQ6m4UdzuZWbxSAiJ4TrWrwRYDCKn8Va72g9UcUdiOyLd6Eg54iSCKdbQ+zELYjhcuwO7g4kpc6V/wgcHYVG4stPyuiXc2G+ZAGXDtW0H7QobeXEUTAsad2AshmCA+lFCmecywBdpsDSYp9ZBY0Qfevncmx0CIWlaPPVjUQ3FMn+oniamJlmbwpmHLiZuCyDE9sSxeQrPSI/7N+zSD03EM6AxIBswaF6XzIhcP3aPz9BzJ2v/YHpPzxtqLaLhEswxWkghmRYASaJn6Ut9xwuWkfhO2UIzkBW6RA3HV6CjZ5opQBe4IyxiVsB2qPzQfxGXz4pN2BoTbuLyf4jS0CA1h6g/7vpCz6VnOuTzBg/c7nQjk8Y69hUYHL91lSlZ/a7tNHe3z9DtaxVg24MG56e+mevYpUgLk="
    bucket: gantry5
    local-dir: "$PROJ_PKGS_PATH"
    upload-dir: nightly
    skip_cleanup: true
    acl: public_read
    on:
      repo: gantry/gantry5
      branch: develop
after_deploy:
  - echo "Branch ($TRAVIS_BRANCH) - Tag ($TRAVIS_TAG)"
  - if [ ! -z "$TRAVIS_TAG" ]; then
      git config user.email "bot@travis-ci.org";
      git config user.name "Travis CI";
      git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";
      git fetch --quiet;
      git checkout develop;
      git reset --hard HEAD;
      cd $TRAVIS_BUILD_DIR/bin/build;
      php build.php prod-versions -Dupdate_versions=true -Dxml.version=$TRAVIS_TAG;
      cd $TRAVIS_BUILD_DIR;
      git commit -am "Release [$TRAVIS_TAG] - Automatic Version Number Updates";
      git push --force --quiet --set-upstream https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git develop:master &>/dev/null;
      curl --user ${BAMBOO_DEPLOY} -X POST -d "stage&executeAllStages&bamboo.variable.IS_RELEASE=yes&&bamboo.variable.THEME_VERSION=${TRAVIS_TAG}" ${BAMBOO_SITE}THEMES-HELIUM;
    fi
  - if [ "$TRAVIS_BRANCH" == 'develop' ]; then
      curl -L http://gantry.org/cibuilds >/dev/null 2>&1;
    fi
