branding:
  css:
    classname: 'particle_gantry_branding'

copyright:
  date:
    start: 2007
    end: now
  owner: 'RocketTheme, LLC'

loginbutton:
  title:
  logintext: Login
  logouttext: Logout
  css:
    classname: 'particle_gantry_loginbutton'

logo:
  image: 'images/logo.png'
  text: 'Gantry'

totop:
  css:
    classname: 'particle_gantry_totop'
