schemes:
  themes:
    type: ReadOnlyStream
    paths:
      - /

  theme:
    type: ReadOnlyStream
    prefixes:
      '':
        - themes://gantry
        - themes://gantry/common

      css/:
        - themes://gantry/css-compiled
        - themes://gantry/css
        - themes://gantry/common/css-compiled
        - themes://gantry/common/css
