settings:
  title: Extended Menu
  base: /

ordering:
  home:

  features:
    - overview:
      positions:
      variations:
      typography:
      menu:
      documentation:
    - another:
        item-3:
        item-1:
        item-2:
      yet-another:
      yet-yet-another:
    - module:

  sample-pages:
    - overview:
      about-us:
        - layout-1:
        - layout-2:
        - layout-3:
      the-team:
        - layout-1:
        - layout-2:
        - layout-3:
      pricing:
        - layout-1:
        - layout-2:
        - layout-3:
    - faq:
        - layout-1:
        - layout-2:
        - layout-3:
      services:
        - layout-1:
        - layout-2:
        - layout-3:
      blog:
        - layout-1:
        - layout-2:
        - layout-3:
    - ricochet:

  special:
    - error:
      offline:
      comingsoon:
    - unsupported:
      component:
      raw:

  styles:
    - preset-1:
      preset-2:
      preset-3:
    - preset-4:
      preset-5:
      preset-6:

  download:
  contact:

items:
  home:
    menu_icon: fa fa-fw fa-home

  features:
    type: alias
    link: features/typography
    title: Features
    browserNav: 0
    params:
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: fa fa-fw fa-bolt
    layout: columns

  features/overview:
    index: 0

  features/positions:
    index: 0

  features/variations:
    index: 0

  features/typography:
    index: 0

  features/menu:
    index: 0

  features/documentation:
    index: 0

  features/another:
    index: 1

  features/another/item-1:
    index: 1

  features/another/item-2:
    index: 1

  features/another/item-3:
    index: 1

  features/yet-another:
    index: 1

  features/yet-yet-another:
    index: 1

  features/module:
    index: 2

  sample-pages:
    type: separator
    title: Sample Pages
    menu_icon: fa fa-fw fa-fire

  sample-pages/about-us:
    type: separator
    title: About Us
    menu_icon: fa fa-fw fa-ra

  sample-pages/the-team:
    type: separator
    title: The Team
    menu_icon: fa fa-fw fa-users

  sample-pages/pricing:
    type: separator
    title: Pricing
    menu_icon: fa fa-fw fa-usd

  sample-pages/faq:
    type: separator
    title: FAQ
    menu_icon: fa fa-fw fa-book

  sample-pages/services:
    type: separator
    title: Services
    menu_icon: fa fa-fw fa-taxi

  sample-pages/blog:
    type: separator
    title: Blog
    menu_icon: fa fa-fw fa-calendar-o

  special:
    type: alias
    link: special/error
    title: Special Pages
    browserNav: 0
    anchor_css:
    anchor_title:
    menu_image:
    menu_icon: fa fa-fw fa-shield

  special/error:
    menu_icon: fa fa-fw fa-warning

  special/unsupported:
    menu_icon: fa fa-fw fa-wheelchair

  special/offline:
    menu_icon: fa fa-fw fa-power-off

  special/comingsoon:
    menu_icon: fa fa-fw fa-paint-brush

  special/component:
    menu_icon: fa fa-fw fa-file-text-o

  special/raw:
    menu_icon: fa fa-fw fa-file-code-o

  styles:
  styles/preset-1:
  styles/preset-2:
  styles/preset-3:
  styles/preset-4:
  styles/preset-5:
  styles/preset-6:

  download:

  contact:

  about:
    visible: false

  team:
    visible: false
