settings:
  title: Main Menu
  base: /

ordering:
  home:
  admin:
    about:
    configurations:
    menu:
    themes:
    learn:

items:
  home:
    menu_icon: fa fa-fw fa-home

  admin:
    type: separator
    title: Admin
    menu_icon: fa fa-fw fa-cogs

  admin/about:
    type: alias
    menu_icon: fa fa-fw fa-question-circle
    link: admin
    title: Theme Admin

  admin/configurations:
    type: alias
    menu_icon: fa fa-fw fa-star
    link: admin/configurations
    title: Configurations

  admin/menu:
    type: alias
    menu_icon: fa fa-fw fa-wrench
    link: admin/menu
    title: Menu Manager

  admin/themes:
    type: alias
    menu_icon: fa fa-fw fa-tint
    link: ../
    title: Back to Themes

  admin/learn:
    type: alias
    menu_icon: fa fa-fw fa-book
    link: ../learn
    title: Documentation