enabled: true

css:
  id:
  class: 'members-list'

members:
  - name: Robert Smith
    role: CEO of Chimera
    image: gantry-prime://images/rocketlauncher/pages/the-team/img-01.jpg
    description: '<p>Hi I am Robert!</p>'

  - name: Matias the Awesome
    role: Lead Developer
    image: gantry-prime://images/rocketlauncher/pages/the-team/img-02.jpg
    description: '<p>rok Rok ROk ROK!</p>'
