schemes:
  gantry-admin:
    type: ReadOnlyStream
    prefixes:
      '':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common
        - templates/gantry

      'assets':
        - administrator/components/com_gantryadmin
        - administrator/components/com_gantryadmin/common
        - templates/gantry
        - templates/gantry/common
